In [1]:
import numpy as np

In [5]:
# 02. create 1D array
np.array([0,1,2,3,4,5,6,7,8,9])
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 03. create a 3*3 boolean array
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
# 04. extract items that satisfy a given condition from 1D array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[~arr %2 == 0]

array([1, 3, 5, 7, 9])

In [11]:
# 05. replace values that satisfies a condition
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[~arr %2 == 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
# 06. replcae w/o affecting original array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.where(arr % 2 == 1, -1, arr)

In [13]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 07. reshape array
np.arange(10).shape

(10,)

In [16]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
# 08. vertically stack arrays
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# 09. horizontally stack 2 arrays
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a,b], axis=1)
np.hstack((a,b))
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [30]:
# 10. generate custom sequences in numpu w/o hardcoding
a = np.array([1,2,3])
np.repeat(a, 3)
np.tile(a,3)
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
# 11. common items between two np arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [33]:
# 12. remove from on array those items that exists in another
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [40]:
# 13. get positions where elements of two array match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7]),)

In [44]:
# 14. extract all numbers b/w a given range from a numpy array
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a >= 5)& (a <= 10)]

array([ 6,  9, 10])

In [47]:
# 15. make the function to work on two scalars
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])

In [48]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [49]:
# 16. swap 2 columns in a 2D np.array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [53]:
# 17. swap 2 rwos in a 2D np array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [56]:
# 18. reverse the rows of a 2D np array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [68]:
# 19. reverse the columns
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [76]:
# 20. create 2D array containing random floats b/w 5 and 10
arr = np.random.randint(5, 10, size=(5,3))

In [2]:
import numpy as np

In [6]:
# 21. print only 3 decimal places in ndarray
rand_arr = np.random.random((5,3))
rand_arr.round(3)

array([[0.612, 0.693, 0.819],
       [0.521, 0.006, 0.546],
       [0.715, 0.461, 0.848],
       [0.625, 0.05 , 0.85 ],
       [0.761, 0.564, 0.039]])

In [9]:
# .set_printoptions(precision=x)를 사용해 반올림 자릿수 설정.
# 한번 설정해놓고 모듈 내내 사용 할 때 편리.
# https://seong6496.tistory.com/182 참고

np.set_printoptions(precision=3)
rand_arr

array([[0.612, 0.693, 0.819],
       [0.521, 0.006, 0.546],
       [0.715, 0.461, 0.848],
       [0.625, 0.05 , 0.85 ],
       [0.761, 0.564, 0.039]])

In [19]:
# 22. pretty print a np array by suppressing the scientific notation(like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [21]:
# 23. limit the number of ittems printed in np array output
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [33]:
# 24. print the full np array without truncating
# 정답은 threshold=np.nan을 하라고 하는데 오류남. 대신 sys.maxsize를 써보라함.
np.set_printoptions(threshold=1000)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
import sys

In [34]:
# 25. import a dataset with numbers and texts keeping the text intact in python numpy
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


FileNotFoundError: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data not found.

In [ ]:
# 26. extract a particular column from 1D array of tuples
